-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: Login

local flatbuffers = require('flatbuffers')

local ReqRoleInfo = {} -- the module
local ReqRoleInfo_mt = {} -- the class metatable

function ReqRoleInfo.New()
    local o = {}
    setmetatable(o, {__index = ReqRoleInfo_mt})
    return o
end
function ReqRoleInfo.GetRootAsReqRoleInfo(buf, offset)
    local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
    local o = ReqRoleInfo.New()
    o:Init(buf, n + offset)
    return o
end
function ReqRoleInfo_mt:Init(buf, pos)
    self.view = flatbuffers.view.New(buf, pos)
end
function ReqRoleInfo_mt:RoleId()
    local o = self.view:Offset(4)
    if o ~= 0 then
        return self.view:String(o + self.view.pos)
    end
end
function ReqRoleInfo.Start(builder) builder:StartObject(1) end
function ReqRoleInfo.AddRoleId(builder, roleId) builder:PrependUOffsetTRelativeSlot(0, roleId, 0) end
function ReqRoleInfo.End(builder) return builder:EndObject() end

return ReqRoleInfo -- return the module