// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum Protocols : uint
{
 ReqLoginGame = 10000,
 ResLoginGame = 10001,
 ResAllItemInfo = 20000,
 ResUpdateItemInfo = 20001,
 ResHeartBeat = 90000,
};

