-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: Login

local flatbuffers = require('flatbuffers')

local ResRoleInfo = {} -- the module
local ResRoleInfo_mt = {} -- the class metatable

function ResRoleInfo.New()
    local o = {}
    setmetatable(o, {__index = ResRoleInfo_mt})
    return o
end
function ResRoleInfo.GetRootAsResRoleInfo(buf, offset)
    local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
    local o = ResRoleInfo.New()
    o:Init(buf, n + offset)
    return o
end
function ResRoleInfo_mt:Init(buf, pos)
    self.view = flatbuffers.view.New(buf, pos)
end
function ResRoleInfo_mt:Result()
    local o = self.view:Offset(4)
    if o ~= 0 then
        return self.view:Get(flatbuffers.N.Int32, o + self.view.pos)
    end
    return 0
end
function ResRoleInfo_mt:RoleInfo()
    local o = self.view:Offset(6)
    if o ~= 0 then
        local x = self.view:Indirect(o + self.view.pos)
        local obj = require('Protocol.Login.RoleInfo').New()
        obj:Init(self.view.bytes, x)
        return obj
    end
end
function ResRoleInfo.Start(builder) builder:StartObject(2) end
function ResRoleInfo.AddResult(builder, result) builder:PrependInt32Slot(0, result, 0) end
function ResRoleInfo.AddRoleInfo(builder, roleInfo) builder:PrependUOffsetTRelativeSlot(1, roleInfo, 0) end
function ResRoleInfo.End(builder) return builder:EndObject() end

return ResRoleInfo -- return the module