-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: System

local flatbuffers = require('flatbuffers')

local ResHeartBeat = {} -- the module
local ResHeartBeat_mt = {} -- the class metatable

function ResHeartBeat.New()
    local o = {}
    setmetatable(o, {__index = ResHeartBeat_mt})
    return o
end
function ResHeartBeat.GetRootAsResHeartBeat(buf, offset)
    local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
    local o = ResHeartBeat.New()
    o:Init(buf, n + offset)
    return o
end
function ResHeartBeat_mt:Init(buf, pos)
    self.view = flatbuffers.view.New(buf, pos)
end
function ResHeartBeat.Start(builder) builder:StartObject(0) end
function ResHeartBeat.End(builder) return builder:EndObject() end

return ResHeartBeat -- return the module