-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: 

local Protocols = {
    ReqLoginGame = 10000,
    ResLoginGame = 10001,
    ReqCreateRole = 10002,
    ResCreateRole = 10003,
    ReqRoleInfo = 10004,
    ResRoleInfo = 10005,
    ResAllItemInfo = 20000,
    ResUpdateItemInfo = 20001,
    ResHeartBeat = 90000,
}

return Protocols -- return the module