// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Protocol.Login
{

using global::System;
using global::FlatBuffers;

public struct ReqCreateRole : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ReqCreateRole GetRootAsReqCreateRole(ByteBuffer _bb) { return GetRootAsReqCreateRole(_bb, new ReqCreateRole()); }
  public static ReqCreateRole GetRootAsReqCreateRole(ByteBuffer _bb, ReqCreateRole obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ReqCreateRole __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string RoleName { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetRoleNameBytes() { return __p.__vector_as_span(4); }
#else
  public ArraySegment<byte>? GetRoleNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetRoleNameArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<ReqCreateRole> CreateReqCreateRole(FlatBufferBuilder builder,
      StringOffset roleNameOffset = default(StringOffset)) {
    builder.StartObject(1);
    ReqCreateRole.AddRoleName(builder, roleNameOffset);
    return ReqCreateRole.EndReqCreateRole(builder);
  }

  public static void StartReqCreateRole(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddRoleName(FlatBufferBuilder builder, StringOffset roleNameOffset) { builder.AddOffset(0, roleNameOffset.Value, 0); }
  public static Offset<ReqCreateRole> EndReqCreateRole(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ReqCreateRole>(o);
  }
};


}
