// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Protocol.Login
{

using global::System;
using global::FlatBuffers;

public struct ReqRoleInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ReqRoleInfo GetRootAsReqRoleInfo(ByteBuffer _bb) { return GetRootAsReqRoleInfo(_bb, new ReqRoleInfo()); }
  public static ReqRoleInfo GetRootAsReqRoleInfo(ByteBuffer _bb, ReqRoleInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ReqRoleInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string RoleId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetRoleIdBytes() { return __p.__vector_as_span(4); }
#else
  public ArraySegment<byte>? GetRoleIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetRoleIdArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<ReqRoleInfo> CreateReqRoleInfo(FlatBufferBuilder builder,
      StringOffset roleIdOffset = default(StringOffset)) {
    builder.StartObject(1);
    ReqRoleInfo.AddRoleId(builder, roleIdOffset);
    return ReqRoleInfo.EndReqRoleInfo(builder);
  }

  public static void StartReqRoleInfo(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddRoleId(FlatBufferBuilder builder, StringOffset roleIdOffset) { builder.AddOffset(0, roleIdOffset.Value, 0); }
  public static Offset<ReqRoleInfo> EndReqRoleInfo(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ReqRoleInfo>(o);
  }
};


}
