// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Protocol.Login
{

using global::System;
using global::FlatBuffers;

public struct ResRoleInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ResRoleInfo GetRootAsResRoleInfo(ByteBuffer _bb) { return GetRootAsResRoleInfo(_bb, new ResRoleInfo()); }
  public static ResRoleInfo GetRootAsResRoleInfo(ByteBuffer _bb, ResRoleInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ResRoleInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Result { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public RoleInfo? RoleInfo { get { int o = __p.__offset(6); return o != 0 ? (RoleInfo?)(new RoleInfo()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<ResRoleInfo> CreateResRoleInfo(FlatBufferBuilder builder,
      int result = 0,
      Offset<RoleInfo> roleInfoOffset = default(Offset<RoleInfo>)) {
    builder.StartObject(2);
    ResRoleInfo.AddRoleInfo(builder, roleInfoOffset);
    ResRoleInfo.AddResult(builder, result);
    return ResRoleInfo.EndResRoleInfo(builder);
  }

  public static void StartResRoleInfo(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddResult(FlatBufferBuilder builder, int result) { builder.AddInt(0, result, 0); }
  public static void AddRoleInfo(FlatBufferBuilder builder, Offset<RoleInfo> roleInfoOffset) { builder.AddOffset(1, roleInfoOffset.Value, 0); }
  public static Offset<ResRoleInfo> EndResRoleInfo(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ResRoleInfo>(o);
  }
};


}
