// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Protocol.Login
{

using global::System;
using global::FlatBuffers;

public struct RoleInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static RoleInfo GetRootAsRoleInfo(ByteBuffer _bb) { return GetRootAsRoleInfo(_bb, new RoleInfo()); }
  public static RoleInfo GetRootAsRoleInfo(ByteBuffer _bb, RoleInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RoleInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string RoleId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetRoleIdBytes() { return __p.__vector_as_span(4); }
#else
  public ArraySegment<byte>? GetRoleIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetRoleIdArray() { return __p.__vector_as_array<byte>(4); }
  public string RoleName { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetRoleNameBytes() { return __p.__vector_as_span(6); }
#else
  public ArraySegment<byte>? GetRoleNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetRoleNameArray() { return __p.__vector_as_array<byte>(6); }
  public int RoleLevel { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<RoleInfo> CreateRoleInfo(FlatBufferBuilder builder,
      StringOffset roleIdOffset = default(StringOffset),
      StringOffset roleNameOffset = default(StringOffset),
      int roleLevel = 0) {
    builder.StartObject(3);
    RoleInfo.AddRoleLevel(builder, roleLevel);
    RoleInfo.AddRoleName(builder, roleNameOffset);
    RoleInfo.AddRoleId(builder, roleIdOffset);
    return RoleInfo.EndRoleInfo(builder);
  }

  public static void StartRoleInfo(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddRoleId(FlatBufferBuilder builder, StringOffset roleIdOffset) { builder.AddOffset(0, roleIdOffset.Value, 0); }
  public static void AddRoleName(FlatBufferBuilder builder, StringOffset roleNameOffset) { builder.AddOffset(1, roleNameOffset.Value, 0); }
  public static void AddRoleLevel(FlatBufferBuilder builder, int roleLevel) { builder.AddInt(2, roleLevel, 0); }
  public static Offset<RoleInfo> EndRoleInfo(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RoleInfo>(o);
  }
};


}
