// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Protocol.Item
{

using global::System;
using global::FlatBuffers;

public struct ResUpdateItemInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ResUpdateItemInfo GetRootAsResUpdateItemInfo(ByteBuffer _bb) { return GetRootAsResUpdateItemInfo(_bb, new ResUpdateItemInfo()); }
  public static ResUpdateItemInfo GetRootAsResUpdateItemInfo(ByteBuffer _bb, ResUpdateItemInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ResUpdateItemInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ItemInfo? ItemInfo { get { int o = __p.__offset(4); return o != 0 ? (ItemInfo?)(new ItemInfo()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<ResUpdateItemInfo> CreateResUpdateItemInfo(FlatBufferBuilder builder,
      Offset<ItemInfo> itemInfoOffset = default(Offset<ItemInfo>)) {
    builder.StartObject(1);
    ResUpdateItemInfo.AddItemInfo(builder, itemInfoOffset);
    return ResUpdateItemInfo.EndResUpdateItemInfo(builder);
  }

  public static void StartResUpdateItemInfo(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddItemInfo(FlatBufferBuilder builder, Offset<ItemInfo> itemInfoOffset) { builder.AddOffset(0, itemInfoOffset.Value, 0); }
  public static Offset<ResUpdateItemInfo> EndResUpdateItemInfo(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ResUpdateItemInfo>(o);
  }
};


}
