// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Protocol
{

using global::System;
using global::FlatBuffers;

public struct ReqLoginGame : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ReqLoginGame GetRootAsReqLoginGame(ByteBuffer _bb) { return GetRootAsReqLoginGame(_bb, new ReqLoginGame()); }
  public static ReqLoginGame GetRootAsReqLoginGame(ByteBuffer _bb, ReqLoginGame obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ReqLoginGame __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span(4); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
  public string Password { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPasswordBytes() { return __p.__vector_as_span(6); }
#else
  public ArraySegment<byte>? GetPasswordBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetPasswordArray() { return __p.__vector_as_array<byte>(6); }
  public int Channel { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int SubChannel { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string ChannelName { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetChannelNameBytes() { return __p.__vector_as_span(12); }
#else
  public ArraySegment<byte>? GetChannelNameBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetChannelNameArray() { return __p.__vector_as_array<byte>(12); }

  public static Offset<ReqLoginGame> CreateReqLoginGame(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset),
      StringOffset passwordOffset = default(StringOffset),
      int channel = 0,
      int subChannel = 0,
      StringOffset channelNameOffset = default(StringOffset)) {
    builder.StartObject(5);
    ReqLoginGame.AddChannelName(builder, channelNameOffset);
    ReqLoginGame.AddSubChannel(builder, subChannel);
    ReqLoginGame.AddChannel(builder, channel);
    ReqLoginGame.AddPassword(builder, passwordOffset);
    ReqLoginGame.AddName(builder, nameOffset);
    return ReqLoginGame.EndReqLoginGame(builder);
  }

  public static void StartReqLoginGame(FlatBufferBuilder builder) { builder.StartObject(5); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static void AddPassword(FlatBufferBuilder builder, StringOffset passwordOffset) { builder.AddOffset(1, passwordOffset.Value, 0); }
  public static void AddChannel(FlatBufferBuilder builder, int channel) { builder.AddInt(2, channel, 0); }
  public static void AddSubChannel(FlatBufferBuilder builder, int subChannel) { builder.AddInt(3, subChannel, 0); }
  public static void AddChannelName(FlatBufferBuilder builder, StringOffset channelNameOffset) { builder.AddOffset(4, channelNameOffset.Value, 0); }
  public static Offset<ReqLoginGame> EndReqLoginGame(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ReqLoginGame>(o);
  }
};


}
