// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Protocol.System
{

using global::System;
using global::FlatBuffers;

public struct ResHeartBeat : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ResHeartBeat GetRootAsResHeartBeat(ByteBuffer _bb) { return GetRootAsResHeartBeat(_bb, new ResHeartBeat()); }
  public static ResHeartBeat GetRootAsResHeartBeat(ByteBuffer _bb, ResHeartBeat obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ResHeartBeat __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartResHeartBeat(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<ResHeartBeat> EndResHeartBeat(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ResHeartBeat>(o);
  }
};


}
